[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install --no-cache-dir -r backend/requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 4 backend.app:app"

[variables]
PYTHONPATH = "/app"
