services:
  - type: web
    name: mj-billing-backend-test
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      cd ..
    startCommand: |
      cd backend
      gunicorn app:app
    envVars:
      - key: PYTHONPATH
        value: .
