services:
  - type: web
    name: mj-billing-backend
    env: python
    plan: free
    runtime: python
    buildCommand: pip install --upgrade pip && pip install --no-cache-dir -r backend/requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONPATH
        value: .
